package org.shirdrn.tuscany.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-10-24T11:04:54.510+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "solrSearchComponent_SolrSearchService", 
                  wsdlLocation = "http://tuscany.server.shiyanjun.cn:8080/solrSearchComponent/SolrSearchService?wsdl",
                  targetNamespace = "http://service.tuscany.shirdrn.org/") 
public class SolrSearchComponentSolrSearchService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.tuscany.shirdrn.org/", "solrSearchComponent_SolrSearchService");
    public final static QName SolrSearchServiceSOAP11Port = new QName("http://service.tuscany.shirdrn.org/", "SolrSearchServiceSOAP11Port");
    static {
        URL url = null;
        try {
            url = new URL("http://tuscany.server.shiyanjun.cn:8080/solrSearchComponent/SolrSearchService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SolrSearchComponentSolrSearchService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://tuscany.server.shiyanjun.cn:8080/solrSearchComponent/SolrSearchService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SolrSearchComponentSolrSearchService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SolrSearchComponentSolrSearchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SolrSearchComponentSolrSearchService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SolrSearchComponentSolrSearchService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SolrSearchComponentSolrSearchService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SolrSearchComponentSolrSearchService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SolrSearchService
     */
    @WebEndpoint(name = "SolrSearchServiceSOAP11Port")
    public SolrSearchService getSolrSearchServiceSOAP11Port() {
        return super.getPort(SolrSearchServiceSOAP11Port, SolrSearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SolrSearchService
     */
    @WebEndpoint(name = "SolrSearchServiceSOAP11Port")
    public SolrSearchService getSolrSearchServiceSOAP11Port(WebServiceFeature... features) {
        return super.getPort(SolrSearchServiceSOAP11Port, SolrSearchService.class, features);
    }

}
