package org.shirdrn.tuscany.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-10-24T11:04:54.430+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://service.tuscany.shirdrn.org/", name = "SolrSearchService")
@XmlSeeAlso({ObjectFactory.class})
public interface SolrSearchService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://service.tuscany.shirdrn.org/", className = "org.shirdrn.tuscany.service.Search")
    @WebMethod
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://service.tuscany.shirdrn.org/", className = "org.shirdrn.tuscany.service.SearchResponse")
    public java.lang.String search(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3
    );
}
